### ISSUE TITLE
please use mainline branch

### ISSUE THREAD

**Issue by sadoneli** [ghostnup/asuswrt-merlin.ng#1]
https://github.com/RMerl/asuswrt-merlin.ng/blob/master/tools/build-all#L144

**Comment by ghostnup** [comment]
I will create another branch when I have time.

**Comment by godcong** [comment]
> I will create another branch when I have time.

我merge了你的代码进了merlin的mainline，能正常使用。但不知道有没有什么别的问题。
如果刷了mainline的cfe会变砖...

**Comment by ghostnup** [comment]
> > I will create another branch when I have time.
> 
> 我merge了你的代码进了merlin的mainline，能正常使用。但不知道有没有什么别的问题。
> 如果刷了mainline的cfe会变砖。。。
> 应为我这没有刷不死固件没法做更进一步测试了。。。
> 
> 我直接在你的分支上改的，你要是愿意的话，我可以pr过来。
> 但代码我有些地方做了些改动。。。
> 
> 我希望大家可以一起去维护一个稳定，可用的梅林版本。

mainline更新的太快了，一两天就一更新，而且也不太稳定，本来适配以后我做的修改也没有大量的时间来测试，如果BUG太多，大家也不知道是我修改的部分出了问题，还是上游源码的问题。而且因为有些修改是因为本来就闭源的，为了慎重起见，这些部分我也没有开源，如果上游源码涉及到这些部分我也要频繁的更新二进制文件，徒增工作量。由于工作原因，现在也没有很多时间来改代码。所以我的想法还是在上游发布了稳定版的基础上再merge，一次性解决conflict，我也希望大家多提交一些PR，我一个人时间精力能力也有限，希望有能力定位问题修改代码的人才能提交PR，如果是上游merlin源码问题提交给源作者，如果是适配问题提交给我。

**Comment by sadoneli** [comment]
相比mainline，master才叫更新快，merlin固件作者都是时不时把master的merge到mainline来着。而且mainline也不用随时去搞合并，等merlin发布一个正式版后再去merge，几个月也就merge一次。

**Comment by godcong** [comment]
> 相比mainline，master才叫更新快，merlin固件作者都是时不时把master的merge到mainline来着。而且mainline也不用随时去搞合并，等merlin发布一个正式版后再去merge，几个月也就merge一次。

我merge了mainline，编译的固件有好多问题。
