### ISSUE TITLE
384.18版本 CPU 占用高问题

### ISSUE THREAD

**Issue by kr1s-gzq** [ghostnup/asuswrt-merlin.ng#11]
384.18版本，k3screenbg 还是占用CPU过高，基本在20%以上
kill 掉之后CPU 2-6%以内
17版本时可以kill掉，18版本kill掉一会又把进程拉起来了
应该是在哪里设置了防杀功能吧
能否在  工具箱 - 屏幕 加一个开关，来选择是否开启k3screenbg的功能

**Comment by evenye** [comment]
我也碰到相同的问题。 无法关掉。能否请楼主提供一个方法出来或以临时关掉呢？ 谢谢！！！！

**Comment by kr1s-gzq** [comment]
384.18.1已经添加开关屏幕功能，辛苦

**Comment by evenye** [comment]
多谢多谢！！！！
