### ISSUE TITLE
真坑，中继模式导致路由器再也进不去后台

### ISSUE THREAD

**Issue by AlibabaDAMO** [ghostnup/asuswrt-merlin.ng#2]
捅菊花没用。
ssh进不去
家里3层，2台k3被我刷废了
紧急之下买了一台ax86对付着用
现在刷费的路由挂咸鱼三天了连个人问都没有

**Comment by HanaForward** [comment]
ttl 线刷会吗？SPI + 编译器 随便刷个CEF 进去会吗？
不会你瞎刷啥啊？官改不能用吗？

**Comment by AlibabaDAMO** [comment]
买了ttl那个usb，依旧进不去，可坑死我了，今天2台95元包邮出掉了，又买了一台ax86，两台ax86够了。

**Comment by godcong** [comment]
cfe模式不行吗?

**Comment by AlibabaDAMO** [comment]
@godcong 试了，进不去，ttl也一样不行，已经出掉了，解放了。

**Comment by HanaForward** [comment]
@AlibabaDAMO  没事就把 issues 关掉

**Comment by ghostnup** [comment]
这个事真不怪我，中继以后IP会更改到你的主路由网段，你IP不对当然进不去，下一个华硕的Device Discovery就能看到路由器的IP，点进去就能设置了。
至于你说TTL进不去，那更不可能，用过TTL的人都知道，不管怎么设置TTL都是能进的，多半是你使用问题。
这个东西不是源码的issues，纯属使用问题，我会关闭掉，请活用论坛搜索或者在论坛询问。
