### ISSUE TITLE
K3 tb 梅林 升级后 无法再进入 软件中心

### ISSUE THREAD

**Issue by HanaForward** [ghostnup/asuswrt-merlin.ng#3]
我是通过官改刷的tb梅林，然后升级刷的这个系统，tb梅林我格式化了jffs分区，升级后软件中心永远卡更新中...
火狐浏览器问题依旧,尝试修改 下次启动时格式化JFFS分区 重启后仍然卡 更新中
df -h 显示挂载在  /dev/ubi0_0 
无法尝试取消挂载

**Comment by HanaForward** [comment]
挂载点无法手动修改，尝试修改Linux 内核选项把

**Comment by HanaForward** [comment]
GET http://router.asus.com/_api/soft?_=15932YYYYYXXX net::ERR_CONNECTION_RESET
请求失败

**Comment by HanaForward** [comment]
check_xss_blacklist: /www/Module_Softcenter.asp is not in www

**Comment by ghostnup** [comment]
试一下flash_eraseall /dev/mtd5

**Comment by godcong** [comment]
> 试一下flash_eraseall /dev/mtd5

软件中心你用的是哪个版本的啊？我koolshare看了下差分和你的不一样。
我fork过去编译了，但是有些人显示不出来。

**Comment by ghostnup** [comment]
> > 试一下flash_eraseall /dev/mtd5
> 
> 软件中心你用的是哪个版本的啊？我koolshare看了下差分和你的不一样。
> 我fork过去编译了，但是有些人显示不出来。
> 我想搞个专门k3的软件中心，然后可以从github上面获取到内容的(国内可以用gitee之类的）这样省去了自己搭服务器得成本。

就koolshare开源的版本https://github.com/koolshare/armsoft/tree/master/softcenter/softcenter，我集成的是1.4版本

**Comment by godcong** [comment]
> > > 试一下flash_eraseall /dev/mtd5
> > 
> > 
> > 软件中心你用的是哪个版本的啊？我koolshare看了下差分和你的不一样。
> > 我fork过去编译了，但是有些人显示不出来。
> > 我想搞个专门k3的软件中心，然后可以从github上面获取到内容的(国内可以用gitee之类的）这样省去了自己搭服务器得成本。
> 
> 就koolshare开源的版本[https://github.com/koolshare/armsoft/tree/master/softcenter/softcenter，我集成的是1.4版本](https://github.com/koolshare/armsoft/tree/master/softcenter/softcenter%EF%BC%8C%E6%88%91%E9%9B%86%E6%88%90%E7%9A%84%E6%98%AF1.4%E7%89%88%E6%9C%AC)

官方没找1.4的最新的也只有1.0.4的,是不是他们闭源删掉了?

**Comment by HanaForward** [comment]
@godcong  出现问题可能是因为跨域访问导致的,用手机就正常访问,电脑ESET关闭后间歇性访问

**Comment by HanaForward** [comment]
我手动替换文件更新至1.0.7 试过 也是一样的 不行

**Comment by HanaForward** [comment]
大致就是 
jffs 挂载成功
软件中心服务启动成功
软件中心服务工作正常
但是电脑访问就是不可以

**Comment by HanaForward** [comment]
没法处理我就关掉了 能处理的时候重新打开吧
