### ISSUE TITLE
网络监控家 - 带宽管理 QoS - 网页浏览历史

### ISSUE THREAD

**Issue by kr1s-gzq** [ghostnup/asuswrt-merlin.ng#4]
打开了 网页浏览历史 功能，但没有任何记录显示
不知道是不是我一个人这种情况，或者是个固件的BUG

**Comment by ghostnup** [comment]
我也没有，应该是bug，至于是源码bug还是适配bug不太好说

**Comment by kr1s-gzq** [comment]
升级到384.18，这个问题就解决了
