### ISSUE TITLE
无线网络 - 专业设置 - 发射功率调整

### ISSUE THREAD

**Issue by kr1s-gzq** [ghostnup/asuswrt-merlin.ng#5]
我调了2.4G和5G的发射功率为23dbm

但用ROG工具获取到的功率还是
2.4G：27.00 dBm / 501.19 mw
5G：   26.00 dBm / 398.11 mw

不知道是功率调整无效还是ROG工具获取有问题

**Comment by ghostnup** [comment]
已修复，感谢反馈
