### ISSUE TITLE
k3screenbg程序占用cpu问题

### ISSUE THREAD

**Issue by kr1s-gzq** [ghostnup/asuswrt-merlin.ng#6]
top查看k3screenbg进程占用cpu和vsz比较高
杀进程前，页面CPU一直在20%左右
杀进程后，页面CPU正常负载的情况3-10%左右

**Comment by HanaForward** [comment]
希望可以自行控制k3screenbg 的开关，反正这个功能 不是谁都要

**Comment by ghostnup** [comment]
k3screenbg之前确实存在内存泄漏，源码已经fix了，等下个版本更新
